server:
  port: 10008
spring:
  application:
    name: eureka-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-feign-hystrix
  host:
    socket-timeout-millis: 3000
    connect-timeout-millis: 3000
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 1000


